name: Update the container pythonproject

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.ACCESS_TOKEN }}
      - 
        name: Check
        uses: actions/checkout@v2
      -      
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./DockerFile
          push: true
          tags: mahdibenzid/exam:1.0.${{github.run_number}}
